create database
htmlacademy-yii/50837-task-force-1 pull request #5
Opened 2020-07-04 15:30 UTC by sergei404

2020-07-04 20:44 UTC, Ovsyanka reviewed
Возьми за привычку всегда проверять, какие именно изменения ты коммитишь. В принципе, в любом GUI это должно быть довольно просто.

Это действительно важно в реальной работе, так как
1. На этом этапе ты лишний (не лишний, на самом деле) раз проверяешь свои изменения.
2. Если ты что-то лишнее зальешь в публичный репозиторий, корректно это убрать может быть сложно. На работе за это можно получить тумаков =)

В данном случае .env и schema.zip попали в коммит по ошибке, их надо будет убрать.

2020-07-04 20:50 UTC, Ovsyanka commented on schema.sql
> +CREATE DATABASE forse CHARACTER SET utf8 COLLATE utf8_general_ci;
Этот скрипт будет падать с ошибкой, что база уже создана, если его запустить повторно.
Поскольку задача скрипта - привести базу в начальное состояние - стоит в самом начале скрипта удалять БД. Заполняться начальными данными она будет другим скриптом, так что удалять базу не страшно.

2020-07-04 21:04 UTC, Ovsyanka commented on schema.sql
> +  name VARCHAR (70) NOT NULL,
70 символов выглядит достаточным на первый взгляд, но если задуматься, этого может и не хватить. Чтобы не оказаться в ситуации, что однажды ты не сможешь сохранить какого-нибудь пользоватля в БД, лучше перестраховыться и выбирать длинну полей с запасом. 255 символов будет вполне уместно.

2020-07-04 21:05 UTC, Ovsyanka commented on schema.sql
> +  email VARCHAR (129) UNIQUE NOT NULL,
Для email [254 символа](https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address).

2020-07-04 21:07 UTC, Ovsyanka commented on schema.sql
> +  discription VARCHAR (256),
В 256 символов можно и не уместиться. Лучше использовать text

2020-07-04 21:17 UTC, Ovsyanka commented on schema.sql
> +  phone INT UNSIGNED,
Телефон - не числовое значение, это текст. То, что он состоит из цифр, не значит, что он - число. Более того, в международном формате он начинается с "+".

2020-07-04 21:25 UTC, Ovsyanka commented on schema.sql
> +  not_show_profile BOOLEAN);
Обычно, не стоит в именах переменных/свойств/колонок и т.п. использовать негатив. Лучше show_profile.

2020-07-04 21:31 UTC, Ovsyanka commented on schema.sql
> +CREATE TABLE job_photos (
job - это место работы, должность, типа того. Тут речь о выполненных работах, а это works.

2020-07-04 21:37 UTC, Ovsyanka commented on schema.sql
> +CREATE TABLE categories (
Для категорий нужен еще столбец с именем иконки. см. categories.csv

2020-07-04 21:43 UTC, Ovsyanka commented on schema.sql
> +CREATE TABLE users_of_categories (
Лучше просто users_categories (или в обратном порядке). А то мало кто поймет, что там за "пользователи категорий" хранятся =)

2020-07-04 21:44 UTC, Ovsyanka commented on schema.sql
> +  categories_id INT,
category_id

2020-07-04 21:44 UTC, Ovsyanka commented on schema.sql
> +  categories_id INT,
UNSIGNED INT

2020-07-04 21:44 UTC, Ovsyanka commented on schema.sql
> +  user_id INT,
UNSIGNED INT

2020-07-04 21:46 UTC, Ovsyanka reviewed
Я в паре мест отметил, но понял, что это у тебя много где - проверь, чтобы типы полей, осуществляющих связи между таблицами были одинаковыми. Например users.id имеет тип INT INSIGNED, но в других таблицаз user_id - просто INT.

2020-07-04 21:50 UTC, Ovsyanka commented on schema.sql
> +  iNeed VARCHAR (129) NOT NULL,
Хороший буквальный перевод "Мне нужно", но по сути это заголовок задания, как я понимаю - в бд лучше его так и хранить как title или name. Это самое "Мне нужно" для интерфейса хорошо, а вот для БД не очень, на мой взгляд. Но если ты не согласен и тебе так нравится - оставь так )

2020-07-04 21:51 UTC, Ovsyanka commented on schema.sql
> +  job_details VARCHAR (512),
job тут лишнее. Просто details. То, что это детали именно задания, а не чего-то там еще понятно из того факта, что эта колонка в таблице заданий

2020-07-04 22:01 UTC, Ovsyanka commented on schema.sql
> +  job_details VARCHAR (512),
Я бы использовал тут TEXT, хотя можно и varchar, но для описания работы 512 символов как-то маловато. Хотя-бы 2-5к символов.

2020-07-04 22:02 UTC, Ovsyanka commented on schema.sql
> +  adress VARCHAR (256),
address

2020-07-04 22:05 UTC, Ovsyanka commented on schema.sql
> +  budget INT,
Правильно, что используешь тут целочисленный тип, а не вещественный! Для финансовых данных это важно, так как вещественные значения по сути всегда приблизительные, а финансы любят точность )

2020-07-04 22:09 UTC, Ovsyanka commented on schema.sql
> +  document VARCHAR (256),
У тебя тут что хранится? Документ? Нет. Тут путь к файлу (который может быть чем угодно, согласно ТЗ, не обязательно документом). Уместно назвать колонку path.

2020-07-04 22:12 UTC, Ovsyanka commented on schema.sql
> +  author_review_id INT,
У тебя колонка в таблице review, не нужно повторять эту информацию еще и в имени колонки. author_id - достаточно. Можно назвать еще author_user_id - чтобы явно отразить в названии, в какой таблице хранятся эти авторы. Я бы выбрал второй вариант, но и первый тоже хорош, учитывая, что по этому полю нужно сделать ограничение внешнего ключа и по нему будет понятно в какой таблице находится значение. Так что делай как тебе больше по нраву.

2020-07-04 22:14 UTC, Ovsyanka commented on schema.sql
> +  user_id INT,
Было бы классно как-то отразить в названии, что это именно тот юзер, на которого написан отклик. Например, reviewed_user_id, target_user_id или как-то еще.

2020-07-04 22:17 UTC, Ovsyanka commented on schema.sql
> +  review VARCHAR (512),
То же самое, что и для других текстовых полей. Лучше TEXT или более длинный VARCHAR.
Название я бы сделал text или content. У тебя есть сущность - отзыв. У него есть много свойств, одно из которых текст. А так получается, что отзыв является свойством отзыва - путаница =)

2020-07-04 22:18 UTC, Ovsyanka commented on schema.sql
> +  data_respond DATETIME);
Дата по английски - date. И не надо посторять тут respond. Просто date.

2020-07-04 22:20 UTC, Ovsyanka commented on schema.sql
> +  user_id INt,
В чем разница между author_id и user_id? Нужен только один.

2020-07-04 22:20 UTC, Ovsyanka commented on schema.sql
> +  report VARCHAR (512));
Может быть text или content?

2020-07-04 22:25 UTC, Ovsyanka commented on schema.sql
> +  adress VARCHAR (256),
А вообще, посмотри ТЗ как должен храниться адрес задания.
> Выбранное значение сохраняется в задании как координаты широты и долготы.

2020-07-04 22:32 UTC, Ovsyanka commented on schema.sql
> +  city VARCHAR (129) NOT NULL,
А чего это у нас город строкой? А таблица городов нам для чего? ;)

2020-07-04 22:33 UTC, Ovsyanka requested changes
Я прошелся по твоей схеме не анализируя достаточно ли там столбцов и таблиц - это довольно трудоемко. Если окажется, что чего-то не хватает - это можно будет добавить позже.
В целом выглядит довольно хорошо. Многие замечания связаны с английским языком и наименованиями столбцов/таблиц.

Много где не указаны ограничения внешнего ключа. Их надо определять всегда, когда есть связь с другой таблицей.

По каждому замечанию задавай себе вопрос - единственное ли это место, к которому применимо замечание. Часто есть другие места, где аналогичная ситуация, но я про них уже не пишу повторно.

2020-07-08 08:40 UTC, sergei404 commented on schema.sql
> +  user_id INt,
автор кто пишет юзер кому пишут

2020-07-08 17:25 UTC, Ovsyanka commented on schema.sql
> +  user_id INt,
Если я правильно понимаю - это таблица для функционала, описанного в "4.10 Отправка сообщения". Там написано
> Выполняется после отправки формы из блока «Переписка» на странице задания.

Соответственно, переписка должна быть привязана к заданию, а получатель тут не нужен.

2020-07-08 17:28 UTC, Ovsyanka commented on schema.sql
> +DROP DATABASE forse;
Только сейчас заметил, что у тебя тут опечатка. Force, а не forse

2020-07-08 17:38 UTC, Ovsyanka commented on schema.sql
> +  length VARCHAR (256)
Тут у нас широта и долгота должны быть, а не ширина и длинна =D
В csv файле cities.csv посмотри - можно использовать сокращенно, как там или полные слова.

Кроме того ,судя по [документации](https://developers.google.com/maps/documentation/geocoding/intro?hl=ru), тип у коорданит, приходящих от google api - вещественные числа, а не строки.

2020-07-08 17:39 UTC, Ovsyanka commented on schema.sql
> +  discription TEXT,
description

2020-07-08 18:29 UTC, Ovsyanka commented on schema.sql
> +  adds_id INT UNSIGNED,
town_id. Слова adds нет в английском, к тому же стоит одну и ту же сущность называть одинаково в разных частях программы.

2020-07-08 18:37 UTC, Ovsyanka commented on schema.sql
> +  translation VARCHAR (256),
Для чего? Вроде не предполагается по ТЗ мультиязычности.

2020-07-10 04:02 UTC, Ovsyanka commented on schema.sql
> +  breadth VARCHAR (256),
breadth означает "ширина", тут же хранится "широта" - latitude

2020-07-10 04:04 UTC, Ovsyanka requested changes
БД не переименована из forse в force.
Тип широты/долготы не поменян на double.

2020-07-10 21:44 UTC, merged